title: Georg Lorenz
description: Assistant Professor | Utrecht University
url: "https://georglorenz.com"
theme: minima

plugins:
  - jekyll-sitemap

header_pages:
  - index.md
  - research.md
  - publications.md
  - cv.md
  - activities.md
